export const TXT = {
  EMPTY: "Sin resultados",
  LOADING: "Cargando…",
  SEARCH: "Buscar…",
  SEARCH_COMMAND: "Buscar comando…",
  SELECT_OPTION: "Selecciona una opción",
  EMPTY_OPTIONS: "Sin opciones",
  CLEAR_SELECTION: "Limpiar selección",
  CLEAR_SEARCH: "Limpiar búsqueda",
  CLEAR_TIME: "Limpiar hora",
  SELECT_TIME: "Seleccionar hora",
  CLOSE_ALERT: "Cerrar alerta",
  CLOSE_MODAL: "Cerrar modal",
  CLOSE_DRAWER: "Cerrar drawer",
  CLOSE_OPTIONS: "Cerrar opciones",
  OPEN_OPTIONS: "Abrir opciones",
  CLOSE_CALENDAR: "Cerrar calendario",
  OPEN_CALENDAR: "Abrir calendario",
  CLOSE_TIME_PICKER: "Cerrar selector de hora",
  OPEN_TIME_PICKER: "Abrir selector de hora",
  PREV_PAGE: "Página anterior",
  NEXT_PAGE: "Página siguiente",
  PAGE_INFO: (n, of) => `Pagina ${n} de ${of}`,
  PAGE_CURRENT: (n) => `Página actual, ${n}`,
  PAGE_GO_TO: (n) => `Ir a la página ${n}`,
};
