export const TXT = {
  EMPTY: "Sin resultados",
  LOADING: "Cargando…",
  SEARCH: "Buscar…",
  SEARCH_COMMAND: "Buscar comando…",
  SELECT_OPTION: "Selecciona una opción",
  EMPTY_OPTIONS: "Sin opciones",
  CLEAR_SELECTION: "Limpiar selección",
  CLEAR_SEARCH: "Limpiar búsqueda",
  CLEAR_TIME: "Limpiar hora",
  SELECT_TIME: "Seleccionar hora",
  CLOSE_ALERT: "Cerrar alerta",
  CLOSE_MODAL: "Cerrar modal",
  CLOSE_DRAWER: "Cerrar drawer",
  CLOSE_OPTIONS: "Cerrar opciones",
  OPEN_OPTIONS: "Abrir opciones",
  CLOSE_CALENDAR: "Cerrar calendario",
  OPEN_CALENDAR: "Abrir calendario",
  CLOSE_TIME_PICKER: "Cerrar selector de hora",
  OPEN_TIME_PICKER: "Abrir selector de hora",
  PREV_PAGE: "Página anterior",
  NEXT_PAGE: "Página siguiente",
  PAGE_INFO: (n, of) => `Pagina ${n} de ${of}`,
  PAGE_CURRENT: (n) => `Página actual, ${n}`,
  PAGE_GO_TO: (n) => `Ir a la página ${n}`,
  DECREMENT: "Decrementar",
  INCREMENT: "Incrementar",
  PREV_MONTH: "Mes anterior",
  NEXT_MONTH: "Mes siguiente",
  PREV_YEAR: "Año anterior",
  NEXT_YEAR: "Año siguiente",
  PREV_YEARS: "Bloque anterior de años",
  NEXT_YEARS: "Bloque siguiente de años",
  DATE_RANGE_PLACEHOLDER: "Fecha inicio – Fecha fin",
  SELECT_DATE: "Seleccionar fecha",
  DATE_DIALOG_LABEL: "Selector de fecha",
  RANGE_DIALOG_LABEL: "Selector de rango de fechas",
  TIME_DIALOG_LABEL: "Selector de hora",
  CANCEL: "Cancelar",
  APPLY: "Aplicar",
  CLOSE_TOAST: "Cerrar",
  SEARCH_COMMAND_ARIA: "Buscar en la paleta de comandos",
  PAGINATION_LABEL: "Paginación",
  MODAL_FALLBACK_LABEL: "Modal",
  DRAWER_FALLBACK_LABEL: "Drawer",
  STEPPER_LABEL: "Progreso",
};
