export const ALERT_THEME_CLASSES = {
  light: {
    soft: {
      neutral: "border-neutral-200 bg-neutral-50 text-neutral-800",
      primary: "border-blue-200 bg-blue-50 text-blue-800",
      secondary: "border-purple-200 bg-purple-50 text-purple-800",
      success: "border-green-200 bg-green-50 text-green-800",
      danger: "border-red-200 bg-red-50 text-red-800",
      warning: "border-amber-200 bg-amber-50 text-amber-800",
      info: "border-cyan-200 bg-cyan-50 text-cyan-800",
      light: "border-neutral-100 bg-white text-neutral-600",
      dark: "border-neutral-400 bg-neutral-200 text-neutral-900",
    },
    ghost: {
      neutral: "border-transparent bg-transparent text-neutral-600 hover:bg-neutral-100 hover:text-neutral-900",
      primary: "border-transparent bg-transparent text-blue-700 hover:bg-blue-50 hover:text-blue-800",
      secondary: "border-transparent bg-transparent text-purple-700 hover:bg-purple-50 hover:text-purple-800",
      success: "border-transparent bg-transparent text-green-700 hover:bg-green-50 hover:text-green-800",
      danger: "border-transparent bg-transparent text-red-700 hover:bg-red-50 hover:text-red-800",
      warning: "border-transparent bg-transparent text-amber-700 hover:bg-amber-50 hover:text-amber-800",
      info: "border-transparent bg-transparent text-cyan-700 hover:bg-cyan-50 hover:text-cyan-800",
      light: "border-transparent bg-transparent text-neutral-400 hover:bg-neutral-50 hover:text-neutral-700",
      dark: "border-transparent bg-transparent text-neutral-800 hover:bg-neutral-200 hover:text-neutral-950",
    },
    outline: {
      neutral: "border-neutral-300 bg-transparent text-neutral-800",
      primary: "border-blue-300 bg-transparent text-blue-800",
      secondary: "border-purple-300 bg-transparent text-purple-800",
      success: "border-green-300 bg-transparent text-green-800",
      danger: "border-red-300 bg-transparent text-red-800",
      warning: "border-amber-300 bg-transparent text-amber-800",
      info: "border-cyan-300 bg-transparent text-cyan-800",
      light: "border-neutral-200 bg-transparent text-neutral-500",
      dark: "border-neutral-500 bg-transparent text-neutral-950",
    },
    solid: {
      neutral: "border-neutral-800 bg-neutral-800 text-white",
      primary: "border-blue-600 bg-blue-600 text-white",
      secondary: "border-purple-600 bg-purple-600 text-white",
      success: "border-green-600 bg-green-600 text-white",
      danger: "border-red-600 bg-red-600 text-white",
      warning: "border-amber-500 bg-amber-500 text-neutral-950",
      info: "border-cyan-600 bg-cyan-600 text-white",
      light: "border-neutral-100 bg-white text-neutral-900",
      dark: "border-neutral-950 bg-neutral-950 text-white",
    },
  },
  dark: {
    soft: {
      neutral: "border-neutral-700 bg-neutral-900 text-neutral-200",
      primary: "border-blue-800 bg-blue-950 text-blue-100",
      secondary: "border-purple-800 bg-purple-950 text-purple-100",
      success: "border-green-800 bg-green-950 text-green-100",
      danger: "border-red-800 bg-red-950 text-red-100",
      warning: "border-amber-800 bg-amber-950 text-amber-100",
      info: "border-cyan-800 bg-cyan-950 text-cyan-100",
      light: "border-neutral-700 bg-neutral-800 text-neutral-200",
      dark: "border-neutral-700 bg-neutral-900 text-white",
    },
    ghost: {
      neutral: "border-transparent bg-transparent text-neutral-400 hover:bg-neutral-800 hover:text-white",
      primary: "border-transparent bg-transparent text-blue-300 hover:bg-blue-500/10 hover:text-blue-200",
      secondary: "border-transparent bg-transparent text-purple-300 hover:bg-purple-500/10 hover:text-purple-200",
      success: "border-transparent bg-transparent text-green-300 hover:bg-green-500/10 hover:text-green-200",
      danger: "border-transparent bg-transparent text-red-300 hover:bg-red-500/10 hover:text-red-200",
      warning: "border-transparent bg-transparent text-amber-300 hover:bg-amber-500/10 hover:text-amber-200",
      info: "border-transparent bg-transparent text-cyan-300 hover:bg-cyan-500/10 hover:text-cyan-200",
      light: "border-transparent bg-transparent text-neutral-300 hover:bg-neutral-800 hover:text-white",
      dark: "border-transparent bg-transparent text-neutral-300 hover:bg-neutral-950 hover:text-white",
    },
    outline: {
      neutral: "border-neutral-700 bg-transparent text-neutral-100",
      primary: "border-blue-500/50 bg-transparent text-blue-300",
      secondary: "border-purple-500/50 bg-transparent text-purple-300",
      success: "border-green-500/50 bg-transparent text-green-300",
      danger: "border-red-500/50 bg-transparent text-red-300",
      warning: "border-amber-500/50 bg-transparent text-amber-300",
      info: "border-cyan-500/50 bg-transparent text-cyan-300",
      light: "border-neutral-500 bg-transparent text-neutral-300",
      dark: "border-neutral-700 bg-transparent text-white",
    },
    solid: {
      neutral: "border-neutral-700 bg-neutral-700 text-white",
      primary: "border-blue-300 bg-blue-300 text-neutral-950",
      secondary: "border-purple-300 bg-purple-300 text-neutral-950",
      success: "border-green-300 bg-green-300 text-neutral-950",
      danger: "border-red-300 bg-red-300 text-neutral-950",
      warning: "border-amber-300 bg-amber-300 text-neutral-950",
      info: "border-cyan-300 bg-cyan-300 text-neutral-950",
      light: "border-neutral-800 bg-neutral-800 text-neutral-100",
      dark: "border-neutral-950 bg-neutral-950 text-white",
    },
  },
};
