export const STEPPER_THEME_CLASSES = {
  light: {
    neutral: {
      dotCurrent: "border-2 border-neutral-900 bg-neutral-900 text-white",
      dot: "border-2 border-neutral-300 bg-white text-neutral-500",
      lineCurrent: "bg-neutral-900",
      line: "bg-neutral-200",
      titleCurrent: "text-neutral-900 font-semibold",
      title: "text-neutral-500",
      descriptionCurrent: "text-neutral-600",
      description: "text-neutral-400",
    },
    primary: {
      dotCurrent: "border-2 border-blue-600 bg-blue-600 text-white",
      dot: "border-2 border-blue-200 bg-white text-blue-500",
      lineCurrent: "bg-blue-600",
      line: "bg-blue-200",
      titleCurrent: "text-blue-900 font-semibold",
      title: "text-blue-600",
      descriptionCurrent: "text-blue-700",
      description: "text-blue-500",
    },
    secondary: {
      dotCurrent: "border-2 border-purple-600 bg-purple-600 text-white",
      dot: "border-2 border-purple-200 bg-white text-purple-500",
      lineCurrent: "bg-purple-600",
      line: "bg-purple-200",
      titleCurrent: "text-purple-900 font-semibold",
      title: "text-purple-600",
      descriptionCurrent: "text-purple-700",
      description: "text-purple-500",
    },
    success: {
      dotCurrent: "border-2 border-green-600 bg-green-600 text-white",
      dot: "border-2 border-green-200 bg-white text-green-500",
      lineCurrent: "bg-green-600",
      line: "bg-green-200",
      titleCurrent: "text-green-900 font-semibold",
      title: "text-green-600",
      descriptionCurrent: "text-green-700",
      description: "text-green-500",
    },
    danger: {
      dotCurrent: "border-2 border-red-600 bg-red-600 text-white",
      dot: "border-2 border-red-200 bg-white text-red-500",
      lineCurrent: "bg-red-600",
      line: "bg-red-200",
      titleCurrent: "text-red-900 font-semibold",
      title: "text-red-600",
      descriptionCurrent: "text-red-700",
      description: "text-red-500",
    },
    warning: {
      dotCurrent: "border-2 border-amber-500 bg-amber-500 text-neutral-950",
      dot: "border-2 border-amber-200 bg-white text-amber-600",
      lineCurrent: "bg-amber-500",
      line: "bg-amber-200",
      titleCurrent: "text-amber-900 font-semibold",
      title: "text-amber-600",
      descriptionCurrent: "text-amber-700",
      description: "text-amber-500",
    },
    info: {
      dotCurrent: "border-2 border-cyan-600 bg-cyan-600 text-white",
      dot: "border-2 border-cyan-200 bg-white text-cyan-500",
      lineCurrent: "bg-cyan-600",
      line: "bg-cyan-200",
      titleCurrent: "text-cyan-900 font-semibold",
      title: "text-cyan-600",
      descriptionCurrent: "text-cyan-700",
      description: "text-cyan-500",
    },
    light: {
      dotCurrent: "border-2 border-neutral-300 bg-white text-neutral-900",
      dot: "border-2 border-neutral-200 bg-white text-neutral-400",
      lineCurrent: "bg-neutral-300",
      line: "bg-neutral-200",
      titleCurrent: "text-neutral-700 font-semibold",
      title: "text-neutral-500",
      descriptionCurrent: "text-neutral-600",
      description: "text-neutral-400",
    },
    dark: {
      dotCurrent: "border-2 border-neutral-950 bg-neutral-950 text-white",
      dot: "border-2 border-neutral-400 bg-neutral-100 text-neutral-600",
      lineCurrent: "bg-neutral-950",
      line: "bg-neutral-300",
      titleCurrent: "text-neutral-950 font-semibold",
      title: "text-neutral-700",
      descriptionCurrent: "text-neutral-800",
      description: "text-neutral-500",
    },
  },
  dark: {
    neutral: {
      dotCurrent: "border-2 border-neutral-100 bg-neutral-100 text-neutral-950",
      dot: "border-2 border-neutral-700 bg-neutral-950 text-neutral-400",
      lineCurrent: "bg-neutral-100",
      line: "bg-neutral-800",
      titleCurrent: "text-neutral-50 font-semibold",
      title: "text-neutral-400",
      descriptionCurrent: "text-neutral-300",
      description: "text-neutral-500",
    },
    primary: {
      dotCurrent: "border-2 border-blue-300 bg-blue-300 text-neutral-950",
      dot: "border-2 border-blue-800 bg-blue-950 text-blue-400",
      lineCurrent: "bg-blue-300",
      line: "bg-blue-800",
      titleCurrent: "text-blue-200 font-semibold",
      title: "text-blue-400",
      descriptionCurrent: "text-blue-300",
      description: "text-blue-500",
    },
    secondary: {
      dotCurrent: "border-2 border-purple-300 bg-purple-300 text-neutral-950",
      dot: "border-2 border-purple-800 bg-purple-950 text-purple-400",
      lineCurrent: "bg-purple-300",
      line: "bg-purple-800",
      titleCurrent: "text-purple-200 font-semibold",
      title: "text-purple-400",
      descriptionCurrent: "text-purple-300",
      description: "text-purple-500",
    },
    success: {
      dotCurrent: "border-2 border-green-300 bg-green-300 text-neutral-950",
      dot: "border-2 border-green-800 bg-green-950 text-green-400",
      lineCurrent: "bg-green-300",
      line: "bg-green-800",
      titleCurrent: "text-green-200 font-semibold",
      title: "text-green-400",
      descriptionCurrent: "text-green-300",
      description: "text-green-500",
    },
    danger: {
      dotCurrent: "border-2 border-red-300 bg-red-300 text-neutral-950",
      dot: "border-2 border-red-800 bg-red-950 text-red-400",
      lineCurrent: "bg-red-300",
      line: "bg-red-800",
      titleCurrent: "text-red-200 font-semibold",
      title: "text-red-400",
      descriptionCurrent: "text-red-300",
      description: "text-red-500",
    },
    warning: {
      dotCurrent: "border-2 border-amber-300 bg-amber-300 text-neutral-950",
      dot: "border-2 border-amber-800 bg-amber-950 text-amber-400",
      lineCurrent: "bg-amber-300",
      line: "bg-amber-800",
      titleCurrent: "text-amber-200 font-semibold",
      title: "text-amber-400",
      descriptionCurrent: "text-amber-300",
      description: "text-amber-500",
    },
    info: {
      dotCurrent: "border-2 border-cyan-300 bg-cyan-300 text-neutral-950",
      dot: "border-2 border-cyan-800 bg-cyan-950 text-cyan-400",
      lineCurrent: "bg-cyan-300",
      line: "bg-cyan-800",
      titleCurrent: "text-cyan-200 font-semibold",
      title: "text-cyan-400",
      descriptionCurrent: "text-cyan-300",
      description: "text-cyan-500",
    },
    light: {
      dotCurrent: "border-2 border-neutral-200 bg-neutral-200 text-neutral-950",
      dot: "border-2 border-neutral-600 bg-neutral-950 text-neutral-300",
      lineCurrent: "bg-neutral-200",
      line: "bg-neutral-800",
      titleCurrent: "text-neutral-50 font-semibold",
      title: "text-neutral-300",
      descriptionCurrent: "text-neutral-200",
      description: "text-neutral-500",
    },
    dark: {
      dotCurrent: "border-2 border-neutral-100 bg-neutral-100 text-neutral-950",
      dot: "border-2 border-neutral-700 bg-neutral-950 text-neutral-400",
      lineCurrent: "bg-neutral-100",
      line: "bg-neutral-800",
      titleCurrent: "text-neutral-50 font-semibold",
      title: "text-neutral-400",
      descriptionCurrent: "text-neutral-300",
      description: "text-neutral-500",
    },
  },
};
