export const TABS_THEME_CLASSES = {
  light: {
    list: "border-neutral-200 bg-neutral-100",
    triggerIdle:
      "text-neutral-500 hover:text-neutral-950 focus-visible:outline-neutral-300",
    triggerActive: {
      neutral: "text-neutral-900",
      primary: "text-blue-800",
      secondary: "text-purple-800",
      success: "text-green-800",
      danger: "text-red-800",
      warning: "text-amber-800",
      info: "text-cyan-800",
      light: "text-neutral-600",
      dark: "text-white",
    },
    bubbleActive: {
      neutral: "border-neutral-200 bg-white",
      primary: "border-blue-200 bg-blue-50",
      secondary: "border-purple-200 bg-purple-50",
      success: "border-green-200 bg-green-50",
      danger: "border-red-200 bg-red-50",
      warning: "border-amber-200 bg-amber-50",
      info: "border-cyan-200 bg-cyan-50",
      light: "border-neutral-100 bg-white",
      dark: "border-neutral-900 bg-neutral-950",
    },
    content: "text-neutral-600",
  },
  dark: {
    list: "border-neutral-800 bg-neutral-900",
    triggerIdle:
      "text-neutral-400 hover:text-neutral-50 focus-visible:outline-neutral-700",
    triggerActive: {
      neutral: "text-neutral-100",
      primary: "text-blue-200",
      secondary: "text-purple-200",
      success: "text-green-200",
      danger: "text-red-200",
      warning: "text-amber-200",
      info: "text-cyan-200",
      light: "text-neutral-200",
      dark: "text-white",
    },
    bubbleActive: {
      neutral: "border-neutral-700 bg-neutral-800",
      primary: "border-blue-800 bg-blue-950",
      secondary: "border-purple-800 bg-purple-950",
      success: "border-green-800 bg-green-950",
      danger: "border-red-800 bg-red-950",
      warning: "border-amber-800 bg-amber-950",
      info: "border-cyan-800 bg-cyan-950",
      light: "border-neutral-600 bg-neutral-800",
      dark: "border-neutral-800 bg-neutral-950",
    },
    content: "text-neutral-300",
  },
};
